apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: nfs-02-100g-rwx
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /mnt/nfs-02
    server: nfs.h2.kxr.me
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-nfs
  volumeMode: Filesystem
