apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldap-auth
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ldap-auth
    repoURL: https://github.com/kxr-gitops/cluster-config.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
